language: node_js
node_js:
- '5'
branches:
  only:
  - /^v[0-9]/
addons:
  code_climate:
    repo_token: 8ab0f72a6e9ad1ef81906be5534c7bf4df93c71219b25506869f69bbeeff4ab6

before_script:
- npm install -g gulp
- npm install -g codeclimate-test-reporter
- npm run build

after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: xRHRprqJ3hElFr7uGHQcHkyfswDumBG+ibYCac0dX/yP8P4DQ3EoK3/Lw0lKRjJDkPBDkDg5r3k36HqCS568/MLe2g3+fLLLqfcn7mG0r02w/0zQtbIQeQ3uL/3BiX7fLDlk8ygj+sCvzb+jy+GzFvH0orbnniS7bkGODCPFK9vx/teHv6/X17cV/Zoq1FUZOmc/hqQmEbHTWBYF6rWgo2Acgq3+TbPYhek8LBK0AFYjTZH0QeAyan2rdVAUWXJQNwD3KmJyvcP01o8ZkCa2vDFhpaSHTOInATrFhUxQNJq4kuaiNh4bDc3VulfqnBh+h8exg1y7H6nzbwc7O3Nr001MlCcdrr2PXhaf04BgZmtHksqZAqbl+VeYUI1E6D5BWQj7vR907Ng/kynJ8oMlogBmxccCT7UKXknbV+2Vh175lPAMdUDO8tj1G0NflivBrw365NjRqGlhYfKprfqPNnnGgCLlykkKriyxsU2pL4oAleWl7IvKk/UAEUMK5IFeZVrFMS/w+HaX8F/iZOr1abq8dGj5tlaAdVnDbtTAGLxiPsgP2vEOKkaoSBxXeLEEuBG/zRLhzphQ0Mlw5v0ydbTH06hVjScQB0iXgB/lJlMuVctMIlEQaWhrFw+V9RczUd///4lSPYOfTI8w8+o6RMiRx4gx0Z5uIepl4YzhYBk=
  on:
    tags: true
    branches: true
